export default function TermsPage() {
  const sections = [
    { title: 'Acceptance of Terms', body: 'By creating an account or using the Métier platform, you agree to these Terms of Service. If you do not agree, do not use the service. These terms constitute a legally binding agreement between you and Métier Career Simulator, Inc.' },
    { title: 'Use of the Service', body: 'Métier grants you a limited, non-exclusive, non-transferable license to use the platform for personal career development purposes. You may not: share accounts, resell access, reverse-engineer the platform, use automated means to interact with simulations, or misrepresent simulation results to employers.' },
    { title: 'User Content', body: 'Content you submit in simulations (task responses, documents) remains your intellectual property. By submitting, you grant Métier a limited license to process and store this content for evaluation purposes and service delivery. We do not claim ownership of your work.' },
    { title: 'AI Evaluation Disclaimer', body: 'Career Readiness Scores are generated by AI and are intended as one signal among many. They are not a guarantee of employment outcomes. Métier does not warrant that any specific score will result in a job offer. Employers use scores at their own discretion.' },
    { title: 'Subscriptions and Billing', body: 'Paid plans are billed monthly or annually. You may cancel at any time; your access continues until the end of your paid period. Refunds are not provided for partial months. Institutional plans are governed by a separate agreement. Prices may change with 30 days notice.' },
    { title: 'Termination', body: 'We may suspend or terminate accounts that violate these terms, engage in fraudulent activity, or misuse the platform. You may delete your account at any time. Upon termination, your data will be deleted per our Privacy Policy retention schedule.' },
    { title: 'Limitation of Liability', body: 'To the maximum extent permitted by law, Métier is not liable for indirect, incidental, special, or consequential damages. Our total liability for any claim is limited to the amount you paid us in the 12 months preceding the claim.' },
    { title: 'Governing Law', body: 'These terms are governed by the laws of the State of California, USA. Disputes will be resolved through binding arbitration under AAA rules, except where you opt out within 30 days of first accepting these terms.' },
  ]

  return (
    <div className="bg-[#080812] min-h-screen pt-28 pb-24">
      <div className="max-w-3xl mx-auto px-6 lg:px-8">
        <div className="mb-12">
          <p className="section-label mb-4">Legal</p>
          <h1 className="font-headline font-black text-white text-5xl tracking-tight mb-4">Terms of Service</h1>
          <p className="text-neutral-500 text-sm font-body">Last updated: May 28, 2026 · Effective: May 28, 2026</p>
        </div>
        <div className="space-y-8">
          {sections.map((s, i) => (
            <div key={s.title} className="bg-white/[0.03] border border-white/8 rounded-2xl p-7">
              <h2 className="font-headline font-bold text-white text-xl mb-3">{i + 1}. {s.title}</h2>
              <p className="text-neutral-400 font-body text-sm leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
