import Link from 'next/link'
import { ArrowRight, Target, FileText, MessageSquare, BarChart3, Upload, Clock } from 'lucide-react'

const phases = [
  {
    step: '01',
    title: 'Select Your Simulation',
    description: 'Browse our library of 50+ career tracks across technology, finance, design, operations, and more. Each simulation is calibrated to a specific job title and seniority level. Filter by industry, difficulty, and estimated completion time.',
    visual: 'track-select',
    detail: 'Every simulation was designed with input from working professionals and hiring managers at top firms.',
  },
  {
    step: '02',
    title: 'Read the Manager Brief',
    description: 'You step into a simulated company on Day 1. Your AI manager sends you a professional onboarding email establishing your context, deliverables, and deadlines. This is your first immersion into the role.',
    visual: 'brief',
    detail: "Manager briefs are generated by GPT-4o and customized to each simulation's industry and seniority level.",
  },
  {
    step: '03',
    title: 'Complete Your Tasks',
    description: "Work through a sequence of 4–6 real-world tasks: documents, analyses, emails, presentations, and decision scenarios. Each task has a structured submission interface designed to match how you'd actually complete that work.",
    visual: 'tasks',
    detail: 'Tasks are designed to match the top deliverables identified in actual job descriptions for each role.',
  },
  {
    step: '04',
    title: 'Receive AI Feedback',
    description: 'Within 10 seconds of each submission, our AI evaluation engine analyzes your work across 5 professional dimensions: accuracy, reasoning, communication, problem-solving, and presentation.',
    visual: 'feedback',
    detail: 'Feedback is specific, actionable, and calibrated to professional standards — not generic rubrics.',
  },
  {
    step: '05',
    title: 'Earn Your Career Readiness Score',
    description: 'On completion, you receive a composite Career Readiness Score (0–100) with a full breakdown. See where you stand compared to thousands of others in the same track.',
    visual: 'score',
    detail: 'Your CRS is the standard signal employers use to evaluate pre-hire candidates sourced through Métier.',
  },
  {
    step: '06',
    title: 'Build Your Portfolio',
    description: 'Every completed deliverable is saved to your portfolio. Make items public, generate a shareable link, and give employers access to real work samples — not just claims on a resume.',
    visual: 'portfolio',
    detail: 'Portfolios are viewed by 200+ employer partners on the Métier platform.',
  },
]

const taskTypes = [
  { icon: <FileText className="w-5 h-5" />, label: 'Document Writing', desc: 'Rich text editor with formatting. Export to PDF.' },
  { icon: <BarChart3 className="w-5 h-5" />, label: 'Data Analysis', desc: 'Upload datasets, produce written analysis reports.' },
  { icon: <MessageSquare className="w-5 h-5" />, label: 'Email Drafting', desc: 'Professional email composer with thread context.' },
  { icon: <Target className="w-5 h-5" />, label: 'Decision Scenarios', desc: 'Workplace scenarios with multi-choice reasoning.' },
  { icon: <Upload className="w-5 h-5" />, label: 'Research Summaries', desc: 'Structured summaries tested for accuracy and depth.' },
  { icon: <Clock className="w-5 h-5" />, label: 'Timed Challenges', desc: 'Optional urgency mode to simulate real deadlines.' },
]

export default function HowItWorksPage() {
  return (
    <div className="bg-primary-500">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        {/* Header */}
        <div className="text-center mb-20">
          <div className="section-label mb-3">The Kinetic Pipeline</div>
          <h1 className="text-5xl lg:text-6xl font-headline font-bold text-white mb-6">
            How Métier Works
          </h1>
          <p className="text-neutral-400 max-w-2xl mx-auto font-body text-lg leading-relaxed">
            Six phases. Continuous performance data. One score that proves you can do the work.
          </p>
        </div>

        {/* Phase steps */}
        <div className="space-y-12 mb-24">
          {phases.map((phase, i) => (
            <div
              key={phase.step}
              className={`grid lg:grid-cols-2 gap-10 items-center ${i % 2 === 1 ? 'lg:flex-row-reverse' : ''}`}
            >
              <div className={i % 2 === 1 ? 'lg:order-2' : ''}>
                <div className="flex items-center gap-3 mb-4">
                  <span className="text-6xl font-headline font-bold text-white/10">{phase.step}</span>
                  <div className="h-px flex-1 bg-white/10" />
                </div>
                <h2 className="text-3xl font-headline font-bold text-white mb-4">{phase.title}</h2>
                <p className="text-neutral-300 font-body leading-relaxed mb-4">{phase.description}</p>
                <div className="p-4 bg-tertiary-500/10 border border-tertiary-500/20 rounded-xl">
                  <p className="text-tertiary-300 text-sm font-body italic">{phase.detail}</p>
                </div>
              </div>

              <div className={`card-dark p-8 min-h-52 flex items-center justify-center ${i % 2 === 1 ? 'lg:order-1' : ''}`}>
                <div className="text-center">
                  <div className="w-16 h-16 rounded-2xl bg-tertiary-500/20 border border-tertiary-500/30 flex items-center justify-center mx-auto mb-4">
                    <span className="text-2xl font-headline font-bold text-tertiary-400">{phase.step}</span>
                  </div>
                  <div className="text-white font-semibold">{phase.title}</div>
                  <div className="text-neutral-400 text-sm mt-2 font-label">Phase {phase.step} of 06</div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Task types */}
        <div className="mb-20">
          <div className="text-center mb-10">
            <h2 className="text-3xl font-headline font-bold text-white mb-3">Task Formats</h2>
            <p className="text-neutral-400 font-body">Six types of professional deliverables — each designed to match how work actually gets done.</p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {taskTypes.map((task) => (
              <div key={task.label} className="card-dark p-6 hover:border-white/20 transition-all duration-200 cursor-default">
                <div className="w-10 h-10 rounded-lg bg-tertiary-500/20 flex items-center justify-center text-tertiary-400 mb-4">
                  {task.icon}
                </div>
                <div className="text-white font-semibold mb-1.5">{task.label}</div>
                <div className="text-neutral-400 text-sm font-body">{task.desc}</div>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div className="text-center card-dark p-14">
          <h2 className="text-4xl font-headline font-bold text-white mb-4">Ready to begin?</h2>
          <p className="text-neutral-400 font-body mb-8 max-w-md mx-auto">
            Start your first simulation free. No credit card. No commitment. Just real work.
          </p>
          <Link href="/signup" className="btn-primary text-base px-10 py-4">
            Start Your Simulation <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </div>
    </div>
  )
}
